name: CI - terraform-aws-vpc-AUY1105-FRF

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  call-terraform-workflow:
    name: Terraform Checks
    uses: ./.github/workflows/terraform.yml
    with:
      path: .

  call-checkov-workflow:
    name: Security Analysis
    uses: ./.github/workflows/checkov.yml
    with:
      path: .
